---
- name: Install wireguard and dependencies
  become: True
  apt:
    package:
      - wireguard
      - linux-image-amd64
      - linux-headers-amd64
      - resolvconf
  when: ansible_os_family == 'Debian'

- name: Configure wireguard tunnels
  become: True
  template:
    src: wg.j2
    dest: "/etc/wireguard/{{ item.name }}.conf"
    mode: 0600
    owner: root
    group: root
  with_items: "{{ wireguard_configurations }}"
  register: wireguard_configurations_results
  notify: restart wireguard tunnels

- name: Enable IP forwarding
  become: True
  sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
  when: wireguard_enable_ip_forwarding
